# This is a basic workflow to help you get started with Actions

name: Black Duck

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the shanko_develop branch
  push:
    branches: [ shanko_develop ]
  pull_request:
    branches: [ shanko_develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '15'
          cache: 'maven'
      - name: Build with Maven
        run: mvn clean install -DskipTests

     
      - name: Run Synopsys Detect
        uses: synopsys-sig/detect-action@v0.3.0
        with:
            scan-mode: RAPID # Can be omitted, since this is the default value
            github-token: ${{ secrets.GITHUB_TOKEN }}
            detect-version: 7.9.0
            blackduck-url: ${{ secrets.BLACKDUCK_URL }}
            blackduck-api-token: ${{ secrets.BLACKDUCK_API_TOKEN }}
